import Layout from "@/components/shared/Layout";
import RainbowKitAndWagmi from "@/components/RainbowKitAndWagmi/RainbowKitAndWagmi";

import "./globals.css";

export const metadata = {
  title: "Chess DApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RainbowKitAndWagmi>
          <Layout>{children}</Layout>
        </RainbowKitAndWagmi>
      </body>
    </html>
  );
}
